sw2.category=シンプル創傷
sw2.missing_module=モジュールが見つかりません
sw2.version_hint=Lua アドオンのバージョン:
sw2.wound_slot=創傷スロット:
sw2.trigger_on_death=NPC 死亡時に創傷を作成
sw2.trigger_ragdoll=ラグドール創傷
sw2.trigger_clientside_corpse=クライアント側の遺体の創傷
sw2.trigger_menu=トリガー

tool.sw2_tool.name=シンプル創傷
tool.sw2_tool.desc=エンティティに創傷を作成します
tool.sw2_tool.scale_x=X スケール
tool.sw2_tool.scale_y=Y スケール
tool.sw2_tool.scale_z=Z スケール
tool.sw2_tool.blood_scale=血の広がり
tool.sw2_tool.apply=適用
tool.sw2_tool.bind_pose=ラグドール姿勢をリセット
tool.sw2_tool.reset=リセット
tool.sw2_tool.print=パラメータを表示
tool.sw2_tool.deform_texture=変形テクスチャ
tool.sw2_tool.project_texture=血液投影テクスチャ
tool.sw2_tool.shader=シェーダー
tool.sw2_tool.litegorec=Lite Gore 互換
tool.sw2_tool.label.bone=ボーン

sw2.shader.VertexDeformation=頂点変形（非ライト）
sw2.shader.EllipsoidClip=楕円クリップ（非ライト）
sw2.shader.VertexDeformationVertexLit=頂点変形
sw2.shader.EllipsoidClipVertexLit=楕円クリップ

sw2.err.unknowboneid=不明なボーン ID
sw2.missing_module_help=バイナリモジュールを読み込めませんでした。最新の Release をダウンロードし、DLL を garrysmod/lua/bin に配置してください。\n%s
sw2.open_release=GitHub Release を開く
