sw2.category=Прості рани
sw2.missing_module=Модуль не виявлено
sw2.version_hint=Версія Lua-аддона:
sw2.wound_slot=Слот рани:
sw2.trigger_on_death=Створювати рани після смерті NPC
sw2.trigger_ragdoll=Рани на регдолі
sw2.trigger_clientside_corpse=Рани на клієнтському трупі
sw2.trigger_menu=Тригери

tool.sw2_tool.name=Проста рана
tool.sw2_tool.desc=Створювати рани на об'єктах
tool.sw2_tool.scale_x=Масштаб X
tool.sw2_tool.scale_y=Масштаб Y
tool.sw2_tool.scale_z=Масштаб Z
tool.sw2_tool.blood_scale=Розліт крові
tool.sw2_tool.apply=Застосувати
tool.sw2_tool.bind_pose=Скинути позу регдола
tool.sw2_tool.reset=Скинути
tool.sw2_tool.print=Показати параметри
tool.sw2_tool.deform_texture=Текстура деформації
tool.sw2_tool.project_texture=Текстура проєкції крові
tool.sw2_tool.shader=Шейдер
tool.sw2_tool.litegorec=Сумісність із Lite Gore
tool.sw2_tool.label.bone=Кістка

sw2.shader.VertexDeformation=Деформація вершин (без освітлення)
sw2.shader.EllipsoidClip=Відсікання еліпсоїдом (без освітлення)
sw2.shader.VertexDeformationVertexLit=Деформація вершин
sw2.shader.EllipsoidClipVertexLit=Відсікання еліпсоїдом

sw2.err.unknowboneid=Невідомий ID кістки
sw2.missing_module_help=Не вдалося завантажити бінарний модуль. Завантажте останній Release і розмістіть DLL у garrysmod/lua/bin.\n%s
sw2.open_release=Відкрити GitHub Release
