sw2.category=Jednoduché rány
sw2.missing_module=Modul nenalezen
sw2.version_hint=Verze Lua doplňku:
sw2.wound_slot=Slot rány:
sw2.trigger_on_death=Vytvořit rány při smrti NPC
sw2.trigger_ragdoll=Rány na ragdollu
sw2.trigger_clientside_corpse=Rány na mrtvole na straně klienta
sw2.trigger_menu=Spouštěče

tool.sw2_tool.name=Jednoduchá rána
tool.sw2_tool.desc=Vytvořit rány na entitách
tool.sw2_tool.scale_x=Měřítko X
tool.sw2_tool.scale_y=Měřítko Y
tool.sw2_tool.scale_z=Měřítko Z
tool.sw2_tool.blood_scale=Rozstřik krve
tool.sw2_tool.apply=Použít
tool.sw2_tool.bind_pose=Obnovit pózu ragdollu
tool.sw2_tool.reset=Obnovit
tool.sw2_tool.print=Zobrazit parametry
tool.sw2_tool.deform_texture=Textura deformace
tool.sw2_tool.project_texture=Textura projekce krve
tool.sw2_tool.shader=Shader
tool.sw2_tool.litegorec=Kompatibilita s Lite Gore
tool.sw2_tool.label.bone=Kost

sw2.shader.VertexDeformation=Deformace vrcholů (bez osvětlení)
sw2.shader.EllipsoidClip=Elipsoidické ořezání (bez osvětlení)
sw2.shader.VertexDeformationVertexLit=Deformace vrcholů
sw2.shader.EllipsoidClipVertexLit=Elipsoidické ořezání

sw2.err.unknowboneid=Neznámé ID kosti
sw2.missing_module_help=Binární modul se nepodařilo načíst. Stáhněte nejnovější Release a umístěte DLL soubory do garrysmod/lua/bin.\n%s
sw2.open_release=Otevřít GitHub Release
