sw2.category=簡單傷口
sw2.missing_module=未偵測到模組
sw2.version_hint=Lua 插件版本：
sw2.wound_slot=傷口槽位：
sw2.trigger_on_death=NPC 死亡時建立傷口
sw2.trigger_ragdoll=布娃娃傷口
sw2.trigger_clientside_corpse=用戶端屍體傷口
sw2.trigger_menu=觸發器

tool.sw2_tool.name=簡單傷口
tool.sw2_tool.desc=為實體建立傷口
tool.sw2_tool.scale_x=X 軸縮放
tool.sw2_tool.scale_y=Y 軸縮放
tool.sw2_tool.scale_z=Z 軸縮放
tool.sw2_tool.blood_scale=血液飛濺
tool.sw2_tool.apply=套用
tool.sw2_tool.bind_pose=重設布娃娃姿勢
tool.sw2_tool.reset=重設
tool.sw2_tool.print=列印參數
tool.sw2_tool.deform_texture=變形紋理
tool.sw2_tool.project_texture=血液投影紋理
tool.sw2_tool.shader=著色器
tool.sw2_tool.litegorec=Lite Gore 相容
tool.sw2_tool.label.bone=骨骼

sw2.shader.VertexDeformation=頂點變形（無光照）
sw2.shader.EllipsoidClip=橢球剔除（無光照）
sw2.shader.VertexDeformationVertexLit=頂點變形
sw2.shader.EllipsoidClipVertexLit=橢球剔除

sw2.err.unknowboneid=未知的骨骼 ID
sw2.missing_module_help=簡單傷口無法載入二進位模組。請下載最新 Release，並將 DLL 放入 garrysmod/lua/bin。\n%s
sw2.open_release=開啟 GitHub Release
