sw2.category=Простые раны
sw2.missing_module=Модуль не обнаружен
sw2.version_hint=Версия Lua-аддона:
sw2.wound_slot=Слот раны:
sw2.trigger_on_death=Создавать раны при смерти NPC
sw2.trigger_ragdoll=Раны на рэгдолле
sw2.trigger_clientside_corpse=Раны на клиентском трупе
sw2.trigger_menu=Триггеры

tool.sw2_tool.name=Простая рана
tool.sw2_tool.desc=Создавать раны на объектах
tool.sw2_tool.scale_x=Масштаб по X
tool.sw2_tool.scale_y=Масштаб по Y
tool.sw2_tool.scale_z=Масштаб по Z
tool.sw2_tool.blood_scale=Разлёт крови
tool.sw2_tool.apply=Применить
tool.sw2_tool.bind_pose=Сбросить позу рэгдолла
tool.sw2_tool.reset=Сбросить
tool.sw2_tool.print=Вывести параметры
tool.sw2_tool.deform_texture=Текстура деформации
tool.sw2_tool.project_texture=Текстура проекции крови
tool.sw2_tool.shader=Шейдер
tool.sw2_tool.litegorec=Совместимость с Lite Gore
tool.sw2_tool.label.bone=Кость

sw2.shader.VertexDeformation=Деформация вершин (без света)
sw2.shader.EllipsoidClip=Отсечение эллипсоидом (без света)
sw2.shader.VertexDeformationVertexLit=Деформация вершин
sw2.shader.EllipsoidClipVertexLit=Отсечение эллипсоидом

sw2.err.unknowboneid=Неизвестный ID кости
sw2.missing_module_help=Не удалось загрузить бинарный модуль. Скачайте последний Release и поместите DLL в garrysmod/lua/bin.\n%s
sw2.open_release=Открыть GitHub Release
