sw2.category=Ferite semplici
sw2.missing_module=Modulo non rilevato
sw2.version_hint=Versione dell'addon Lua:
sw2.wound_slot=Slot ferita:
sw2.trigger_on_death=Crea ferite alla morte degli NPC
sw2.trigger_ragdoll=Ferite sui ragdoll
sw2.trigger_clientside_corpse=Ferite sui cadaveri lato client
sw2.trigger_menu=Trigger

tool.sw2_tool.name=Ferita semplice
tool.sw2_tool.desc=Crea ferite sulle entità
tool.sw2_tool.scale_x=Scala X
tool.sw2_tool.scale_y=Scala Y
tool.sw2_tool.scale_z=Scala Z
tool.sw2_tool.blood_scale=Diffusione del sangue
tool.sw2_tool.apply=Applica
tool.sw2_tool.bind_pose=Ripristina posa ragdoll
tool.sw2_tool.reset=Ripristina
tool.sw2_tool.print=Mostra parametri
tool.sw2_tool.deform_texture=Texture di deformazione
tool.sw2_tool.project_texture=Texture di proiezione del sangue
tool.sw2_tool.shader=Shader
tool.sw2_tool.litegorec=Compatibilità Lite Gore
tool.sw2_tool.label.bone=Osso

sw2.shader.VertexDeformation=Deformazione vertici (senza luce)
sw2.shader.EllipsoidClip=Ritaglio ellissoidale (senza luce)
sw2.shader.VertexDeformationVertexLit=Deformazione vertici
sw2.shader.EllipsoidClipVertexLit=Ritaglio ellissoidale

sw2.err.unknowboneid=ID osso sconosciuto
sw2.missing_module_help=Impossibile caricare il modulo binario. Scarica l'ultima Release e inserisci le DLL in garrysmod/lua/bin.\n%s
sw2.open_release=Apri GitHub Release
