sw2.category=Heridas simples
sw2.missing_module=Módulo no detectado
sw2.version_hint=Versión del addon Lua:
sw2.wound_slot=Ranura de herida:
sw2.trigger_on_death=Crear heridas al morir los NPC
sw2.trigger_ragdoll=Heridas en ragdolls
sw2.trigger_clientside_corpse=Heridas en cadáveres del cliente
sw2.trigger_menu=Disparadores

tool.sw2_tool.name=Herida simple
tool.sw2_tool.desc=Crear heridas en entidades
tool.sw2_tool.scale_x=Escala X
tool.sw2_tool.scale_y=Escala Y
tool.sw2_tool.scale_z=Escala Z
tool.sw2_tool.blood_scale=Expansión de la sangre
tool.sw2_tool.apply=Aplicar
tool.sw2_tool.bind_pose=Restablecer pose del ragdoll
tool.sw2_tool.reset=Restablecer
tool.sw2_tool.print=Mostrar parámetros
tool.sw2_tool.deform_texture=Textura de deformación
tool.sw2_tool.project_texture=Textura de proyección de sangre
tool.sw2_tool.shader=Shader
tool.sw2_tool.litegorec=Compatibilidad con Lite Gore
tool.sw2_tool.label.bone=Hueso

sw2.shader.VertexDeformation=Deformación de vértices (sin luz)
sw2.shader.EllipsoidClip=Recorte elipsoidal (sin luz)
sw2.shader.VertexDeformationVertexLit=Deformación de vértices
sw2.shader.EllipsoidClipVertexLit=Recorte elipsoidal

sw2.err.unknowboneid=ID de hueso desconocido
sw2.missing_module_help=No se pudo cargar el módulo binario. Descarga la última Release y coloca los DLL en garrysmod/lua/bin.\n%s
sw2.open_release=Abrir GitHub Release
