sw2.category=Einfache Wunden
sw2.missing_module=Modul nicht erkannt
sw2.version_hint=Lua-Addon-Version:
sw2.wound_slot=Wundplatz:
sw2.trigger_on_death=Wunden beim Tod von NPCs erzeugen
sw2.trigger_ragdoll=Ragdoll-Wunden
sw2.trigger_clientside_corpse=Clientseitige Leichenwunden
sw2.trigger_menu=Auslöser

tool.sw2_tool.name=Einfache Wunde
tool.sw2_tool.desc=Wunden auf Entitäten erzeugen
tool.sw2_tool.scale_x=X-Skalierung
tool.sw2_tool.scale_y=Y-Skalierung
tool.sw2_tool.scale_z=Z-Skalierung
tool.sw2_tool.blood_scale=Blutausbreitung
tool.sw2_tool.apply=Anwenden
tool.sw2_tool.bind_pose=Ragdoll-Pose zurücksetzen
tool.sw2_tool.reset=Zurücksetzen
tool.sw2_tool.print=Parameter ausgeben
tool.sw2_tool.deform_texture=Verformungstextur
tool.sw2_tool.project_texture=Blutprojektionstextur
tool.sw2_tool.shader=Shader
tool.sw2_tool.litegorec=Lite-Gore-Kompatibilität
tool.sw2_tool.label.bone=Knochen

sw2.shader.VertexDeformation=Vertexdeformation (ohne Licht)
sw2.shader.EllipsoidClip=Ellipsoid-Ausschnitt (ohne Licht)
sw2.shader.VertexDeformationVertexLit=Vertexdeformation
sw2.shader.EllipsoidClipVertexLit=Ellipsoid-Ausschnitt

sw2.err.unknowboneid=Unbekannte Knochen-ID
sw2.missing_module_help=Das Binärmodul konnte nicht geladen werden. Lade das neueste Release herunter und lege die DLLs in garrysmod/lua/bin ab.\n%s
sw2.open_release=GitHub-Release öffnen
