sw2.category=Proste rany
sw2.missing_module=Nie wykryto modułu
sw2.version_hint=Wersja dodatku Lua:
sw2.wound_slot=Slot rany:
sw2.trigger_on_death=Twórz rany po śmierci NPC
sw2.trigger_ragdoll=Rany na ragdollu
sw2.trigger_clientside_corpse=Rany na zwłokach po stronie klienta
sw2.trigger_menu=Wyzwalacze

tool.sw2_tool.name=Prosta rana
tool.sw2_tool.desc=Twórz rany na obiektach
tool.sw2_tool.scale_x=Skala X
tool.sw2_tool.scale_y=Skala Y
tool.sw2_tool.scale_z=Skala Z
tool.sw2_tool.blood_scale=Rozprysk krwi
tool.sw2_tool.apply=Zastosuj
tool.sw2_tool.bind_pose=Resetuj pozę ragdolla
tool.sw2_tool.reset=Resetuj
tool.sw2_tool.print=Wyświetl parametry
tool.sw2_tool.deform_texture=Tekstura deformacji
tool.sw2_tool.project_texture=Tekstura projekcji krwi
tool.sw2_tool.shader=Shader
tool.sw2_tool.litegorec=Zgodność z Lite Gore
tool.sw2_tool.label.bone=Kość

sw2.shader.VertexDeformation=Deformacja wierzchołków (bez światła)
sw2.shader.EllipsoidClip=Przycięcie elipsoidą (bez światła)
sw2.shader.VertexDeformationVertexLit=Deformacja wierzchołków
sw2.shader.EllipsoidClipVertexLit=Przycięcie elipsoidą

sw2.err.unknowboneid=Nieznane ID kości
sw2.missing_module_help=Nie udało się załadować modułu binarnego. Pobierz najnowsze wydanie i umieść pliki DLL w garrysmod/lua/bin.\n%s
sw2.open_release=Otwórz GitHub Release
