sw2.category=Simple Wound
sw2.missing_module=Module not detected
sw2.version_hint=Lua addon version:
sw2.wound_slot=Wound slot:
sw2.trigger_on_death=Create wounds on NPC death
sw2.trigger_ragdoll=Ragdoll wounds
sw2.trigger_clientside_corpse=Clientside corpse wounds
sw2.trigger_menu=Trigger

tool.sw2_tool.name=Simple Wound
tool.sw2_tool.desc=Create wounds on entities
tool.sw2_tool.scale_x=X scale
tool.sw2_tool.scale_y=Y scale
tool.sw2_tool.scale_z=Z scale
tool.sw2_tool.blood_scale=Blood spread
tool.sw2_tool.apply=Apply
tool.sw2_tool.bind_pose=Reset ragdoll pose
tool.sw2_tool.reset=Reset
tool.sw2_tool.print=Print parameters
tool.sw2_tool.deform_texture=Deformed texture
tool.sw2_tool.project_texture=Projected blood texture
tool.sw2_tool.shader=Shader
tool.sw2_tool.litegorec=Lite Gore compatibility
tool.sw2_tool.label.bone=Bone

sw2.shader.VertexDeformation=Vertex deformation (unlit)
sw2.shader.EllipsoidClip=Ellipsoid clip (unlit)
sw2.shader.VertexDeformationVertexLit=Vertex deformation
sw2.shader.EllipsoidClipVertexLit=Ellipsoid clip

sw2.err.unknowboneid=Unknown bone ID
sw2.missing_module_help=Simple Wound could not load its binary module. Download the latest release and place the DLLs in garrysmod/lua/bin.\n%s
sw2.open_release=Open GitHub Release
