sw2.category=Enkla sår
sw2.missing_module=Modulen hittades inte
sw2.version_hint=Lua-tilläggets version:
sw2.wound_slot=Sårplats:
sw2.trigger_on_death=Skapa sår när NPC dör
sw2.trigger_ragdoll=Ragdoll-sår
sw2.trigger_clientside_corpse=Klientsidiga liksår
sw2.trigger_menu=Utlösare

tool.sw2_tool.name=Enkelt sår
tool.sw2_tool.desc=Skapa sår på entiteter
tool.sw2_tool.scale_x=X-skala
tool.sw2_tool.scale_y=Y-skala
tool.sw2_tool.scale_z=Z-skala
tool.sw2_tool.blood_scale=Blodspridning
tool.sw2_tool.apply=Tillämpa
tool.sw2_tool.bind_pose=Återställ ragdoll-pose
tool.sw2_tool.reset=Återställ
tool.sw2_tool.print=Visa parametrar
tool.sw2_tool.deform_texture=Deformationstextur
tool.sw2_tool.project_texture=Blodprojektionstextur
tool.sw2_tool.shader=Shader
tool.sw2_tool.litegorec=Kompatibilitet med Lite Gore
tool.sw2_tool.label.bone=Ben

sw2.shader.VertexDeformation=Vertexdeformation (utan ljus)
sw2.shader.EllipsoidClip=Ellipsoidurklippning (utan ljus)
sw2.shader.VertexDeformationVertexLit=Vertexdeformation
sw2.shader.EllipsoidClipVertexLit=Ellipsoidurklippning

sw2.err.unknowboneid=Okänt ben-ID
sw2.missing_module_help=Det binära modulen kunde inte läsas in. Ladda ner den senaste releasen och placera DLL-filerna i garrysmod/lua/bin.\n%s
sw2.open_release=Öppna GitHub-release
