sw2.category=Eenvoudige wonden
sw2.missing_module=Module niet gevonden
sw2.version_hint=Lua-addonversie:
sw2.wound_slot=Wondslot:
sw2.trigger_on_death=Maak wonden bij NPC-dood
sw2.trigger_ragdoll=Ragdollwonden
sw2.trigger_clientside_corpse=Client-side lijkwonden
sw2.trigger_menu=Triggers

tool.sw2_tool.name=Eenvoudige wond
tool.sw2_tool.desc=Maak wonden op entiteiten
tool.sw2_tool.scale_x=X-schaal
tool.sw2_tool.scale_y=Y-schaal
tool.sw2_tool.scale_z=Z-schaal
tool.sw2_tool.blood_scale=Bloedverspreiding
tool.sw2_tool.apply=Toepassen
tool.sw2_tool.bind_pose=Ragdollhouding resetten
tool.sw2_tool.reset=Resetten
tool.sw2_tool.print=Parameters weergeven
tool.sw2_tool.deform_texture=Vervormingstextuur
tool.sw2_tool.project_texture=Bloedprojectietextuur
tool.sw2_tool.shader=Shader
tool.sw2_tool.litegorec=Lite Gore-compatibiliteit
tool.sw2_tool.label.bone=Bot

sw2.shader.VertexDeformation=Vertexvervorming (zonder licht)
sw2.shader.EllipsoidClip=Ellipsoïde-uitsnede (zonder licht)
sw2.shader.VertexDeformationVertexLit=Vertexvervorming
sw2.shader.EllipsoidClipVertexLit=Ellipsoïde-uitsnede

sw2.err.unknowboneid=Onbekende bot-ID
sw2.missing_module_help=De binaire module kon niet worden geladen. Download de nieuwste release en plaats de DLL's in garrysmod/lua/bin.\n%s
sw2.open_release=GitHub-release openen
